# Generated by Django 4.2.9 on 2024-01-17 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serendipity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, null=True)),
                ('subject', models.TextField(max_length=600, verbose_name='Serendipity')),
                ('visit', models.IntegerField(null=True)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_ip', models.CharField(max_length=120, null=True)),
                ('writer', models.ForeignKey(default=pages.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='serendipity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
