# Generated by Django 4.2.9 on 2024-01-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serendipity',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='serendipity',
            name='temp2',
        ),
    ]
