# Generated by Django 4.2.8 on 2024-01-03 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('journal_name', models.CharField(max_length=100, null=True)),
                ('abstract', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Best Paper'), (6, 'Minor Revision'), (7, 'Rejected')], default=1)),
                ('journal_type', models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.IntegerField(default=1)),
                ('ack', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_year', models.CharField(blank=True, max_length=10)),
                ('extras', models.CharField(blank=True, max_length=50, null=True)),
                ('all_authors', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
