# Generated by Django 4.2.8 on 2024-01-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='journals/'),
        ),
    ]
