# Generated by Django 4.2.9 on 2024-01-08 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0002_journal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='writer',
            field=models.ForeignKey(default=publications.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journals', to=settings.AUTH_USER_MODEL),
        ),
    ]
