# Generated by Django 4.2.9 on 2024-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_journal_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Best Paper'), (6, 'Minor Revision'), (7, 'Rejected')], default=1, null=True),
        ),
    ]
