# Generated by Django 4.2.9 on 2024-01-08 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_journal_journal_type_alter_journal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='write_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
