# Generated by Django 4.2.9 on 2024-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_journal_update_date_alter_journal_write_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='pub_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
