# Generated by Django 4.2.9 on 2024-01-08 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0006_alter_journal_pub_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('conference_name', models.CharField(max_length=100, null=True)),
                ('abstract', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Best Paper'), (6, 'Minor Revision'), (7, 'Rejected')], default=1, null=True)),
                ('conference_type', models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1, null=True)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('visit', models.IntegerField(default=1)),
                ('ack', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_year', models.CharField(blank=True, max_length=10, null=True)),
                ('extras', models.CharField(blank=True, max_length=50, null=True)),
                ('all_authors', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='conference/')),
                ('writer', models.ForeignKey(default=publications.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
