# Generated by Django 4.2.9 on 2024-01-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Published'), (6, 'Best Paper'), (7, 'Minor Revision'), (8, 'Rejected')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Published'), (6, 'Best Paper'), (7, 'Minor Revision'), (8, 'Rejected')], default=1, null=True),
        ),
    ]
