# Generated by Django 4.2.9 on 2024-01-16 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_conference_status_alter_journal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Preparation'), (2, 'Submitted'), (3, 'Under Review'), (4, 'Accepted'), (5, 'Published'), (6, 'Best Paper'), (7, 'Minor Revision'), (8, 'Rejected')], default=1, null=True)),
                ('write_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.CharField(max_length=100)),
                ('visit', models.IntegerField(default=1)),
                ('tcp_ip', models.CharField(max_length=100, null=True)),
                ('patent_type', models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1)),
            ],
        ),
    ]
