# Generated by Django 4.2.9 on 2024-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='is_international',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
