# Generated by Django 4.2.9 on 2024-01-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_patent_is_international_alter_patent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='is_international',
        ),
        migrations.AlterField(
            model_name='patent',
            name='status',
            field=models.IntegerField(choices=[(1, 'International'), (2, 'Domestic')], default=1, null=True),
        ),
    ]
