# Generated by Django 4.2.9 on 2024-01-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_remove_patent_is_international_alter_patent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
