# Generated by Django 4.2.9 on 2024-01-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_alter_patent_patent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
