# Generated by Django 4.2.9 on 2024-01-09 08:36

# import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('career', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(choices=[(1, 'PROFESSOR'), (2, 'POSTDOC'), (3, 'FULL-TIME')], default=1)),
                ('link', models.URLField(blank=True, null=True)),
                ('email_list', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bio_images/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
