# Generated by Django 4.2.9 on 2024-01-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_bio_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.AddField(
            model_name='bio',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
    ]
