# Generated by Django 4.2.9 on 2024-01-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_bio_user_remove_member_address_bio_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='research_area',
            field=models.TextField(default='AI, Blockchain'),
            preserve_default=False,
        ),
    ]
