# Generated by Django 4.2.9 on 2024-01-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_bio_research_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
