# Generated by Django 4.2.9 on 2024-01-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_bio_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='bio',
            name='email_list',
            field=models.CharField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='position',
            field=models.IntegerField(choices=[(1, 'PROFESSOR'), (2, 'POSTDOC'), (3, 'FULL-TIME'), (4, 'PART-TIME'), (5, 'ADVISERS'), (6, 'ALUMNI (Graduate Students)'), (7, 'ALUMNI (POSTDOC)'), (8, 'Undergraduates'), (9, 'Visiting Researchers')], default=1),
        ),
        migrations.AlterField(
            model_name='bio',
            name='research_area',
            field=models.CharField(),
        ),
    ]
