# Generated by Django 4.2.9 on 2024-01-15 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_dt', models.DateTimeField(default=works.models.default_from_date)),
                ('to_dt', models.DateTimeField(default=works.models.default_from_date)),
                ('paper_progress', models.TextField()),
                ('paper_prog_percen', models.IntegerField()),
                ('paper_last_week', models.TextField()),
                ('paper_this_week', models.TextField()),
                ('project_progress', models.TextField()),
                ('project_prog_percen', models.IntegerField()),
                ('project_last_week', models.TextField()),
                ('project_this_week', models.TextField()),
                ('mnth_gls', models.TextField()),
                ('annl_gls', models.TextField()),
                ('user', models.CharField(blank=True, null=True)),
                ('writer', models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
