# Generated by Django 4.2.9 on 2024-01-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_alter_weeklyreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='is_post_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='user',
            field=models.CharField(blank=True, null=True),
        ),
    ]
