# Generated by Django 4.2.9 on 2024-01-15 06:15

from django.db import migrations, models
import django.utils.timezone
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_weeklyreport_is_post_doc_alter_weeklyreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='writer',
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='annl_gls',
            field=models.TextField(verbose_name='Annual Goals'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='fr_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='is_post_doc',
            field=models.BooleanField(default=False, verbose_name='Post Doc?'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='mnth_gls',
            field=models.TextField(verbose_name='Monthly Goals'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='paper_last_wk',
            field=models.TextField(verbose_name='Last Week Paper'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='paper_prog_percent',
            field=models.IntegerField(verbose_name='Paper Progress Percent'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='paper_progress',
            field=models.TextField(verbose_name='Paper Progress'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='paper_this_wk',
            field=models.TextField(verbose_name='This Week Paper'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='project_last_wk',
            field=models.TextField(verbose_name='Last Week Project'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='project_prog_percent',
            field=models.IntegerField(verbose_name='Paper Progress Percent'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='project_progress',
            field=models.TextField(verbose_name='Project Progress'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='project_this_wk',
            field=models.TextField(verbose_name='Last Week Project'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='to_dt',
            field=models.DateTimeField(default=works.models.default_from_date, verbose_name='Till'),
        ),
    ]
