# Generated by Django 4.2.9 on 2024-01-15 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0009_remove_weeklyreport_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='writer',
            field=models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
