# Generated by Django 4.2.9 on 2024-01-16 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import works.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0010_weeklyreport_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDocReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date')),
                ('to_dt', models.DateTimeField(default=works.models.default_from_date, verbose_name='Till')),
                ('paper_progress', models.TextField(verbose_name='Paper Progress')),
                ('project_progress', models.TextField(verbose_name='Project Progress')),
                ('mnth_gls', models.TextField(verbose_name='Monthly Goals')),
                ('annl_gls', models.TextField(verbose_name='Annual Goals')),
                ('writer', models.ForeignKey(default=works.models.get_default_user, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_doc_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
