# Generated by Django 4.2.9 on 2024-01-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_postdocreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdocreport',
            name='user',
            field=models.CharField(blank=True, null=True),
        ),
    ]
